version: '3'
services:
   device:
    container_name: device
    restart: always
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8070:8070"
    volumes:
      - './:/home/device'
      - /home/device/node_modules/
    depends_on:
      - mongoDevice
   mongoDevice:
    container_name: mongoDevice
    restart: always
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=device_db
   mongo-seed:
    build: ./src/adapters/database/mongo/
    links:
      - mongoDevice
